# Generated by Django 3.1.3 on 2021-06-30 19:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EmployeePosition',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Nazwa')),
                ('color', models.CharField(default='#000000', help_text='typ HEX', max_length=10, verbose_name='Kolor tekstu i ikony')),
                ('bgcolor', models.CharField(default='#FF000000', help_text='typ HEX', max_length=10, verbose_name='Kolor tła')),
                ('icon', models.CharField(blank=True, help_text='typ HTML', max_length=200, verbose_name='Ikona')),
            ],
            options={
                'verbose_name': 'Stanowisko',
                'verbose_name_plural': 'Stanowiska',
            },
        ),
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Nazwa')),
            ],
            options={
                'verbose_name': 'Grupa',
                'verbose_name_plural': 'Grupy',
            },
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(blank=True, max_length=50, verbose_name='Imię')),
                ('last_name', models.CharField(blank=True, max_length=50, verbose_name='Nazwisko')),
                ('birth_date', models.DateField(blank=True, null=True, verbose_name='Data urodzenia')),
                ('phone', models.CharField(blank=True, max_length=50, verbose_name='Telefon')),
                ('group', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='database.group', verbose_name='Grupa')),
                ('position', models.ForeignKey(blank=True, help_text='Wybierz profil pracownika', null=True, on_delete=django.db.models.deletion.CASCADE, to='database.employeeposition', verbose_name='Stanowisko pracownika')),
                ('user', models.OneToOneField(help_text='Wybierz konto pracownika do podpięcia. Konto musi być zarejestrowane', null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Konto pracownika')),
            ],
            options={
                'verbose_name': 'Pracownik',
                'verbose_name_plural': 'Pracownicy',
            },
        ),
    ]
