# Generated by Django 3.1.3 on 2021-06-30 20:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0003_car'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='car',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='database.car', verbose_name='Samochód'),
        ),
    ]
